import {
  a11yDark, a11yLight, agate, anOldHope, androidstudio, arduinoLight, arta, ascetic, atelierCaveDark,
  atelierCaveLight, atelierDuneDark, atelierDuneLight, atelierEstuaryDark, atelierEstuaryLight, atelierForestDark,
  atelierForestLight, atelierHeathDark, atelierHeathLight, atelierLakesideDark, atelierLakesideLight,
  atelierPlateauDark, atelierPlateauLight, atelierSavannaDark, atelierSavannaLight, atelierSeasideDark,
  atelierSeasideLight, atelierSulphurpoolDark, atelierSulphurpoolLight, atomOneDark, atomOneDarkReasonable,
  atomOneLight, brownPaper, codepenEmbed, colorBrewer, darcula, dark, defaultStyle, docco, dracula, far, foundation,
  github, githubGist, gml, googlecode, gradientDark, gradientLight, grayscale, gruvboxDark, gruvboxLight, hopscotch,
  hybrid, idea, irBlack, isblEditorDark, isblEditorLight, kimbieDark, kimbieLight, lightfair, lioshi, magula,
  monoBlue, monokai, monokaiSublime, nightOwl, nnfx, nnfxDark, nord, obsidian, ocean, paraisoDark, paraisoLight,
  pojoaque, purebasic, qtcreatorDark, qtcreatorLight, railscasts, rainbow, routeros, schoolBook, shadesOfPurple,
  solarizedDark, solarizedLight, srcery, stackoverflowDark, stackoverflowLight, sunburst, tomorrow, tomorrowNight,
  tomorrowNightBlue, tomorrowNightBright, tomorrowNightEighties, vs, vs2015, xcode, xt256, zenburn,
} from 'react-syntax-highlighter/dist/esm/styles/hljs'

export default {
  'a11y-dark': a11yDark,
  'a11y-light': a11yLight,
  'agate': agate,
  'an-old-hope': anOldHope,
  'androidstudio': androidstudio,
  'arduino-light': arduinoLight,
  'arta': arta,
  'ascetic': ascetic,
  'atelier-cave-dark': atelierCaveDark,
  'atelier-cave-light': atelierCaveLight,
  'atelier-dune-dark': atelierDuneDark,
  'atelier-dune-light': atelierDuneLight,
  'atelier-estuary-dark': atelierEstuaryDark,
  'atelier-estuary-light': atelierEstuaryLight,
  'atelier-forest-dark': atelierForestDark,
  'atelier-forest-light': atelierForestLight,
  'atelier-heath-dark': atelierHeathDark,
  'atelier-heath-light': atelierHeathLight,
  'atelier-lakeside-dark': atelierLakesideDark,
  'atelier-lakeside-light': atelierLakesideLight,
  'atelier-plateau-dark': atelierPlateauDark,
  'atelier-plateau-light': atelierPlateauLight,
  'atelier-savanna-dark': atelierSavannaDark,
  'atelier-savanna-light': atelierSavannaLight,
  'atelier-seaside-dark': atelierSeasideDark,
  'atelier-seaside-light': atelierSeasideLight,
  'atelier-sulphurpool-dark': atelierSulphurpoolDark,
  'atelier-sulphurpool-light': atelierSulphurpoolLight,
  'atom-one-dark': atomOneDark,
  'atom-one-dark-reasonable': atomOneDarkReasonable,
  'atom-one-light': atomOneLight,
  'brown-paper': brownPaper,
  'codepen-embed': codepenEmbed,
  'color-brewer': colorBrewer,
  'darcula': darcula,
  'dark': dark,
  'default-style': defaultStyle,
  'docco': docco,
  'dracula': dracula,
  'far': far,
  'foundation': foundation,
  'github': github,
  'github-gist': githubGist,
  'gml': gml,
  'googlecode': googlecode,
  'gradient-dark': gradientDark,
  'gradient-light': gradientLight,
  'grayscale': grayscale,
  'gruvbox-dark': gruvboxDark,
  'gruvbox-light': gruvboxLight,
  'hopscotch': hopscotch,
  'hybrid': hybrid,
  'idea': idea,
  'ir-black': irBlack,
  'isbl-editor-dark': isblEditorDark,
  'isbl-editor-light': isblEditorLight,
  'kimbie.dark': kimbieDark,
  'kimbie.light': kimbieLight,
  'lightfair': lightfair,
  'lioshi': lioshi,
  'magula': magula,
  'mono-blue': monoBlue,
  'monokai': monokai,
  'monokai-sublime': monokaiSublime,
  'night-owl': nightOwl,
  'nnfx': nnfx,
  'nnfx-dark': nnfxDark,
  'nord': nord,
  'obsidian': obsidian,
  'ocean': ocean,
  'paraiso-dark': paraisoDark,
  'paraiso-light': paraisoLight,
  'pojoaque': pojoaque,
  'purebasic': purebasic,
  'qtcreator-ark': qtcreatorDark,
  'qtcreator-light': qtcreatorLight,
  'railscasts': railscasts,
  'rainbow': rainbow,
  'routeros': routeros,
  'school-book': schoolBook,
  'shades-of-purple': shadesOfPurple,
  'solarized-dark': solarizedDark,
  'solarized-light': solarizedLight,
  'srcery': srcery,
  'stackoverflow-dark': stackoverflowDark,
  'stackoverflow-light': stackoverflowLight,
  'sunburst': sunburst,
  'tomorrow': tomorrow,
  'tomorrow-night': tomorrowNight,
  'tomorrow-night-blue': tomorrowNightBlue,
  'tomorrow-night-bright': tomorrowNightBright,
  'tomorrow-night-eighties': tomorrowNightEighties,
  'vs': vs,
  'vs2015': vs2015,
  'xcode': xcode,
  'xt256': xt256,
  'zenburn': zenburn,
}